name: damagelisten
version: '${project.version}'
main: me.chengzi.damagelisten.Damagelisten


commands:
  Damagelisten:
    description: 使用/damagelisten reload重载 Damagelisten 插件的配置
    usage: /<command> reload
